backbone: "SIGLIP-ViT-B/16"
resolution: 224

output_dir: null
print_freq: 10

seed: 0
deterministic: True
gpu: 0
num_workers: 8
prec: "amp"

num_epochs: 10
batch_size: 64
micro_batch_size: 64
lr: 0.01
weight_decay: 5e-4
momentum: 0.9
loss_type: "Proden"
classifier: "CosineClassifier"

init_head: None
tte: False
expand: 24